[project]
name = "get-class-schedule"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ics>=0.7.2",
    "pyinstaller>=6.14.1",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.4",
    "selenium>=4.33.0",
]
